### PR TITLE
Fix create availability bug

### LINKED ISSUE #95: Error response when creating a new availability
Error: 
```
{
  "status": 500,
  "error": "Internal Server Error"
}
```

Steps to recreate: 
- Create two users with opposite language learning goals (they could be paired)
- Don't create any availabilities
- Attempt to create an availability for either user

Workaround used during demo:
- Used SQL to insert availability for one of the users
- Then I was able to create an availability for the other user in graphiql

### PR DESCRIPTION
**Pull request by leahriffell**
### What was changed?
- Was previously getting 500 error when: 
  - Create two users with opposite language learning goals (they could be paired)
  - Don't create any availabilities
  - Attempt to create an availability for either user 
- To fix: return empty array instead of nil when return availabilities_to_pair (availability model) doesn't have any matching availabilities
  - This was throwing an error because when there's an existing user with opposite language goals and no matching availabilities, the return value is []. When there's no user with opposite language goals, the return value was nil. So I standardized the return value to always be an array for handling in schedule_pairing.

### Have Tests Been Added?
- [ ] No.
- [ ] Yes, but all tests are not passing.
- [x] Yes, and all are passing.

### Issues:
* Closes #95

### Tracking and Documentation Consistency:
- [x] Updated README where necessary
- [x] Added appropriate labels
- [x] Addressed any rubocop violations
- [x] Added comments on my pull request, particularly in hard-to-understand areas

### CODE REVIEW

File: app/models/availability.rb [hunk 1]
```diff
@@ -7,17 +7,17 @@ class Availability < ApplicationRecord
...
+    return [] if people_to_pair.empty?
+
+    Availability.where(start_date_time: start_date_time..end_date_time)
+                .or(Availability.where(end_date_time: start_date_time..end_date_time))
+                .or(Availability.where('availabilities.start_date_time < ?', start_date_time).where(
+                      'availabilities.end_date_time > ?', end_date_time
+                    ))
+                .where.not(user_id: user_id)
+                .where.not(user_id: user.blocked_ids)
+                .where(status: 'open').where(user_id: people_to_pair.first.user_id)
```
Comment (leahriffell) [inline app/models/availability.rb:20]: This was throwing an error because when there's an existing user with opposite language goals and no matching availabilities, the return value is []. When there's no user with opposite language goals, the return value was nil. So I standardized the return value to always be an array for handling in schedule_pairing.

File: app/graphql/mutations/availabilities/create_availability.rb [hunk 2]
```diff
@@ -12,10 +12,12 @@ def resolve(params:)
...
-        pairing = Pairing.create_pairing(availability, open_slot) unless open_slot.nil?
-        availability.update(status: 'fulfilled') unless pairing.nil?
-        open_slot[0].update(status: 'fulfilled') unless pairing.nil?
+        open_slot = availability.availabilities_to_pair
+        unless open_slot.empty?
+          Pairing.create_pairing(availability, open_slot)
+          availability.update(status: 'fulfilled')
+          open_slot[0].update(status: 'fulfilled')
+        end
       end
```
Comment (leahriffell) [inline app/graphql/mutations/availabilities/create_availability.rb:21]: Now this method will always expect an array instead of an array or nil.
