### PR TITLE
Fix bug for new availability for user without any user languages

### LINKED ISSUE #97: When user tries to create an availability and they don't have any user languages, there is an error response.

### PR DESCRIPTION
**Pull request by leahriffell**
### What was changed?
- Bug: when user tried to create a new availability but didn't have any user languages, 500 error
- Resolved with error message: `user must first have user languages in order to create availability` 

### Have Tests Been Added?
- [ ] No.
- [ ] Yes, but all tests are not passing.
- [x] Yes, and all are passing.

### Issues:
* Closes #97

### Tracking and Documentation Consistency:
- [x] Updated README where necessary
- [x] Added appropriate labels
- [x] Addressed any rubocop violations
- [x] Added comments on my pull request, particularly in hard-to-understand areas

### CODE REVIEW

File: app/graphql/mutations/availabilities/update_availability.rb [hunk 1]
```diff
@@ -17,8 +17,8 @@ def resolve(arguments)
       end
 
       def schedule_pairing(availability)
-        unless availability.status == 'cancelled' || availability.status == 'fulfilled'
-          open_slot = availability.find_availabilities_to_pair
+        if availability.status == 'open'
```
Comment (lkriffell) [inline app/graphql/mutations/availabilities/update_availability.rb:20]: Nice catch here. Idk why I decided to check with the negative

File: app/graphql/mutations/availabilities/create_availability.rb [hunk 2]
```diff
@@ -6,16 +6,24 @@ class CreateAvailability < ::Mutations::BaseMutation
 
       def resolve(params:)
         availability_params = Hash params
+        return handle_no_languages_error if User.find(availability_params[:user_id]).user_languages.empty?
```
Comment (lkriffell) [inline app/graphql/mutations/availabilities/create_availability.rb:9]: Dope

**Review by lkriffell — APPROVED** [review]
Nice job with the bugfix and refactoring my strange code!
